### ISSUE TITLE
Registered command does not show up on the client

### ISSUE THREAD

**Issue by amitojsingh366** [MeguminSama/discord-slash-commands#1]
I tried registering a slash command as stated in README.md but it won't show up on the discord client. I can see it in the list that is returned from `getApplicationCommands()` but it won't show in the client why? Tried it on canary and the normal one.

**Comment by MeguminSama** [comment]
you need to register the applications.commands scope for your bot to the guild

**Comment by MeguminSama** [comment]
ah also the commands are most likely locked behind experiments

you would need to enable that first

**Comment by amitojsingh366** [comment]
Oh ok. Yea lol now it shows up. Thanks a lot!
