### ISSUE TITLE
snowflake type should be PascalCase

### ISSUE THREAD

**Issue by pizzafox** [MeguminSama/discord-slash-commands#12]
https://github.com/MeguminSama/discord-slash-commands/blob/73d2a33badfa40d388733a00748b1a8c209e3907/src/structures/Snowflake.ts#L1

Although this type is an alias of a primitive type, it's not itself a primitive type and therefore should follow the convention of PascalCase names.

**Comment by MeguminSama** [comment]
Thanks for pointing this out!

I'll sneak this into the PR when we ship tests.

**Comment by MeguminSama** [comment]
fixed in https://github.com/MeguminSama/discord-slash-commands/commit/2472216715cb53b824c932950e1149a885836fe4
