### ISSUE TITLE
No file dist/index.js but in dist/src/index.js

### ISSUE THREAD

**Issue by Bryanoxx** [MeguminSama/discord-slash-commands#18]
Hello !

On the 1.2.2 the package works well, on the 1.3.0 I have this error when importing it :
[screenshot](http://puu.sh/H4kCj/2fed74a69f.png)

The problem seems to be the "main" entry in the package.json that points to "dist/index.js" instead of "dist/src/index.js".

I don't think i'm the only one, it would be weird if so 🤔

Great job by the way, i love you package 👍

**Comment by MeguminSama** [comment]
I'm surprised nobody pointed this out sooner!
Thanks for letting me know - I'll check this out ASAP

**Comment by Bryanoxx** [comment]
Yeah I was surprised too !

**Comment by MeguminSama** [comment]
Fix is being deployed now.
Thanks for the help!
