### ISSUE TITLE
How fix?

### ISSUE THREAD

**Issue by megavirus2** [MeguminSama/discord-slash-commands#20]
![image](https://user-images.githubusercontent.com/52457549/106660470-b0cbf600-65a8-11eb-9831-d70710bc9e19.png)

**Comment by ZeroTwoDev** [comment]
just don't use await smh

**Comment by megavirus2** [comment]
![image](https://user-images.githubusercontent.com/52457549/106660731-0bfde880-65a9-11eb-8dd6-6b6da388da57.png)

**Comment by MeguminSama** [comment]
please test this in node first, rather than evaluating through your bot.

also see the examples provided, and also read up on how async/await works in js

I'll be closing this issue as it is out of scope.
