### ISSUE TITLE
Editing slash commands uses the wrong HTTP method

### ISSUE THREAD

**Issue by Rodentman87** [MeguminSama/discord-slash-commands#6]
**Describe the problem**
In the docs it says to use PATCH to update commands, not sure if this is a new thing or not, but trying to edit a command now gives a 405: Method Not Allowed.

**To Reproduce**
1. Create a slash command
2. Try to edit the slash command

**Expected behavior**
Edits the slash command

**Screenshots**
![image](https://user-images.githubusercontent.com/13522833/102118488-5ebaef80-3e05-11eb-9fd5-08e600ece881.png)

**Environment (please complete the following information):**
 - Node.JS version: 14.7.0
 - Operating System Ubuntu 20.04 LTS on Windows 10 x86_64
 - Package version 1.2.0

**Comment by MeguminSama** [comment]
Resolved in https://github.com/MeguminSama/discord-slash-commands/pull/7
