### ISSUE TITLE
[FEAT] Adding tests

### ISSUE THREAD

**Issue by MeguminSama** [MeguminSama/discord-slash-commands#8]
I believe we need to add some tests, to make sure everything works properly when we make new releases.

**Comment by A5rocks** [comment]
I believe the main issue here is: how do we test? Most of the things here are just types, which you can't really check are the ones Discord provides. I guess we can test the verification function and mock the requests to make sure we send the right things, though the second just feels wrong.

**Comment by MeguminSama** [comment]
just testing the create/edit/delete/get methods and ensuring the responses map to the types is enough. so that we know for certain the library works before publishing a release
